version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /db/nestaws:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - adminer
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - /app/node_modules
      - .:/app:delegated
