export enum PROVIDERS {
  RECIPE_SERVICE = 'RECIPE_SERVICE',
  RECIPE_REPOSITORY = 'RECIPE_REPOSITORY',
  LOGGER_SERVICE = 'LOGGER_SERVICE',
  CRYPTO_SERVICE = 'CRYPTO_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  JWT_SERVICE = 'JWT_SERVICE',
  TOKEN_REPOSITORY = 'TOKEN_REPOSITORY',
  TOKEN_SERVICE = 'TOKEN_SERVICE',
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_SERVICE = 'USER_SERVICE',
  S3_SERVICE = 'S3_SERVICE',
  S3_CLIENT = 'S3_CLIENT',
}
